version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine-slim
    ports:
      - 80:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/static:/usr/share/nginx/html/static"
    depends_on:
      - Dvireview

  Dvireview:
    container_name: dvireview
    image: ${username}/dvireview:test 
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${mongouser}
     - MONGO_INITDB_ROOT_PASSWORD=${mongopass}
    depends_on:
     - -mongodb-headless
  
  -mongodb-headless:  
    container_name: mongo
    image: mongo:6.0.4
    volumes:
      - mongo-data:/data/db
      - ./nginx/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    environment:
      - MONGO_INITDB_DATABASE=dvireview
      - MONGO_INITDB_ROOT_USERNAME=${mongouser}
      - MONGO_INITDB_ROOT_PASSWORD=${mongopass}


volumes:
  mongo-data:
  
