name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker network create some-net && docker build . --file Dockerfile --tag dvirstore:latest
    - name: build mongodb image 
      run: docker run -d --network some-net --name mongo mongo:6.0.4
    - name: run the app
      run: docker run -d --network some-net -p 80:5000 --name app dvirstore:latest
    - name: Test the app
      run: |
        sleep 10
        curl -i localhost
        curl -i localhostavailable-books



