name: Docker Image CI

on: 
  push:
    branches:
      - work*
      - feature/*
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   env:
    #     mongouser: ${{ secrets.MONGOUSER }}
    #     mongopass: ${{ secrets.MONGOPASS }}
    #   run: |
    #    docker build -t dvireview:test .
    #    docker build -t nginx:test nginx/
    #    docker compose up -d 

    # - name: Test the app
    #   run: |
    #     docker ps -a
    #     bash e2e-tests/e2e.sh

    - name: Bump version and push tag
      #if: ${{ github.ref == 'refs/heads/main'}}
      id: tag
      uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.KEYSSSSS }}
        WITH_V: false
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.0.0
        VERBOSE: true
        DEFAULT_BRANCH: "main"
      
    - name: tag the image
      #if: ${{ github.ref == 'refs/heads/main'}}
      run: |
        docker tag nginx:test us-docker.pkg.dev/task-1-375619/port-nginx/port-nginx:$(git describe --tags)
        docker tag dvireview:test  us-docker.pkg.dev/task-1-375619/dvireview/dvireview:$(git describe --tags)

    - name: Google Auth
      if: ${{ github.ref == 'refs/heads/main'}}
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        
    
    - name: Docker Auth
      if: ${{ github.ref == 'refs/heads/main'}}
      run: gcloud auth configure-docker us-docker.pkg.dev

    - name: push the image
      if: ${{ github.ref == 'refs/heads/main'}}
      run: |
        docker push us-docker.pkg.dev/task-1-375619/dvireview/dvireview:$(git describe --tags)
        docker push us-docker.pkg.dev/task-1-375619/port-nginx/port-nginx:$(git describe --tags)
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    - name: gitops
      uses: actions/checkout@v3
      with:
        repository: dvir-pashut/port-charts
        token: ${{ secrets.KEYSSSSS }}
        ref: main

    - name: check
      run: |
        echo "${{ steps.tag.outputs.new_tag }}"

