name: Docker Image CI

on:
  push:
    branches: *

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
      run: |
       docker build -t ${username}/dvirstore:test .
       docker compose up -d 
    - name: Test the app
      run: |
        bash e2e-tests/e2e.sh

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.KEYSSSSS }}
        WITH_V: false
        DEFAULT_BUMP: patch
        INITIAL_VERSION: 1.0.0
        VERBOSE: true
        DEFAULT_BRANCH: "main"
      
    - name: echo the tag
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
      run: |
       docker tag ${username}/dvirstore:test   ${username}/dvirstore:$(git describe --tags)

    
    - name: Log in to Docker Hub
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $username -p $password

    - name: push the image 
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dvirstore:$(git describe --tags)