name: Docker Image CI

on: 
  push:
    branches:
      - work*
      - feature/*
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        mongouser: ${{ secrets.MONGOUSER }}
        mongopass: ${{ secrets.MONGOPASS }}
      run: |
       docker build -t dvireview:test .
       #docker compose up -d 

    # - name: Test the app
    #   run: |
    #     docker ps -a
    #     bash e2e-tests/e2e.sh

    # - name: Bump version and push tag
    #   if: ${{ github.ref == 'refs/heads/main'}}
    #   uses: anothrNick/github-tag-action@1.61.0 # Don't use @master unless you're happy to test the latest version
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.KEYSSSSS }}
    #     WITH_V: false
    #     DEFAULT_BUMP: patch
    #     INITIAL_VERSION: 1.0.0
    #     VERBOSE: true
    #     DEFAULT_BRANCH: "main"
      
    - name: tag the image
      # if: ${{ github.ref == 'refs/heads/main'}}
      run: |
       docker tag dvireview:test  us-docker.pkg.dev/task-1-375619/dvireview/dvireview:$(git describe --tags)

    
    # - name: Log in to Docker Hub
    #   if: ${{ github.ref == 'refs/heads/main'}}
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push the image
      # if: ${{ github.ref == 'refs/heads/main'}}
      run: |
        docker push us-docker.pkg.dev/task-1-375619/dvireview/dvireview:$(git describe --tags)
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}