name: Bump version
on:
  push:
    branches:
      - feature/*
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
      run: |
       docker build -t ${username}/dvirstore:test .
       docker compose up -d 
    
    
    - name: Test the app
      run: |
        bash e2e-tests/e2e.sh


        